<!DOCTYPE html>
<html>
<head>
    <title>Event</title>
</head>
<body>
    <h1>${event.name}</h1>
    <p>${event.description}</p>
    <p>Date: ${event.date}</p>
    <!-- <form action="/registrations/register" method="post">
        <input type="hidden" name="event.id" value="${event.id}" />
        <button type="submit">Register</button>
    </form> -->
    <!-- sdf -->
    <br>
    <a href="/">Main</a>
</body>
</html>
