<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="/signup" method="post">
        <div><label> Name : <input type="text" name="name"/> </label></div>
        <div><label> Email: <input type="text" name="email"/> </label></div>
        <div><label> Password: <input type="text" name="password"/> </label></div>
        <div><input type="submit" value="Signup"/></div>
    </form>

    <br>
    <a href="/">Main</a>
</body>
</html>